site_name: uCode

site_author: Ben Marshall

theme: readthedocs

repo_name: https://github.com/ben-marshall/microcoder

markdown_extensions:
- smarty
- sane_lists
- footnotes

pages:
- Overview: README.md
- Usage: usage.md
- Programs: 
  - Overview: programs.md
  - Ports: programs-ports.md
  - State: programs-variables.md
  - Instructions: programs-instructions.md
  - Writing Programs: programs-writing.md
- Architecture: architecture.md
- Example - DMA: example-dma.md
